import pygame as pg
pg.init()
FONT = pg.font.Font(None, 30)
MINIFONT = pg.font.Font(None, 16)

DEBUG = False
COLOR_BLACK                = (0,0,0)
COLOR_WHITE                = (255, 255, 255)
COLOR_CADMIUM_YELLOW       = (254, 236, 0)
COLOR_HANSA_YELLOW         = (252, 211, 0)
COLOR_CADMIUM_ORANGE       = (255, 105, 0)
COLOR_CADMIUM_RED          = (255, 39, 2)
COLOR_QUINACRIDONE_MAGENTA = (128, 2, 46)
COLOR_COBALT_VIOLET        = (78, 0, 66)
COLOR_ULTRAMARINE_BLUE     = (25, 0, 89)
COLOR_COBALT_BLUE          = (0, 33, 133)
COLOR_PHTHALO_BLUE         = (13, 27, 68)
COLOR_PHTHALO_GREEN        = (0, 60, 50)
COLOR_PERMANENT_GREEN      = (7, 109, 22)
COLOR_SAP_GREEN            = (107, 148, 4)
COLOR_BURNT_SIENNA         = (123, 72, 0)
COLOR_DICT = {
    "Black": COLOR_BLACK,
    "White": COLOR_WHITE,
    "Cadmium yellow": COLOR_CADMIUM_YELLOW,
    "Hansa yellow": COLOR_HANSA_YELLOW,
    "Cadmium orange": COLOR_CADMIUM_ORANGE,
    "Cadmium red": COLOR_CADMIUM_RED,
    "Quinacridone magenta": COLOR_QUINACRIDONE_MAGENTA,
    "Cobalt violet": COLOR_COBALT_VIOLET,
    "Ultramarine blue": COLOR_ULTRAMARINE_BLUE,
    "Cobalt blue": COLOR_COBALT_BLUE,
    "Phthalo blue": COLOR_PHTHALO_BLUE,
    "Phthalo green": COLOR_PHTHALO_GREEN,
    "Permanent green": COLOR_PERMANENT_GREEN,
    "Sap green": COLOR_SAP_GREEN,
    "Burnt sienna": COLOR_BURNT_SIENNA,
}
COLOR_FONT = COLOR_COBALT_BLUE
COLOR_BG = COLOR_WHITE
COLOR_WINDOW = (230, 230, 230)
COLOR_BUTTON = COLOR_BG
COLOR_PALETTE = (210, 180, 140)
MAX_PALETTE_LENGTH = 6
DEFAULT_PALETTE = [
    COLOR_CADMIUM_RED,
    COLOR_ULTRAMARINE_BLUE,
    COLOR_CADMIUM_YELLOW,
    COLOR_WHITE,
]
DEFAULT_LEVELS = [
    COLOR_BLACK,
    COLOR_CADMIUM_RED,
    COLOR_CADMIUM_YELLOW,
]

DIM_SCREEN = (800, 600)
DIM_WINDOW = (550, 300)
POS_WINDOW = (150, 150)
DIM_BUCKET_RAD = 45
DELTA_BUCKET = 100
DIM_PALETTE = (650, 110)
DIM_BUCKET_BOX = (2*DIM_BUCKET_RAD,2*DIM_BUCKET_RAD)
POS_PALETTE = (DIM_SCREEN[0]/2. - DIM_PALETTE[0]/2, 500 - DIM_PALETTE[1]/2)
DIM_BUTTON_BOX = (150,40)
DIM_LEVEL_BOX = (300,100)
POS_BUTTON_QUIT     = (20, 0)
POS_BUTTON_NEW      = (20, 50)
POS_BUTTON_MODE     = (20, 100)
POS_BUTTON_PALETTE = (20, 150)
POS_BUTTON_RESET    = (20,400)
POS_BUTTON_CHECK = (600, 400)
POS_BUTTON_LEVEL = (400, 100)
POS_DEBUG = (700, 50)

HEALTH_PER_CLICK = 10


MODE_ZEN = "zen"
MODE_LEVELED = "leveled"
